[[pages]]
path = "home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "data.py"
name = "Data"
icon = "ğŸ”­"

[[pages]]
path = "model.py"
name = "Model"
icon = "ğŸŒˆ"

[[pages]]
path = "infer.py"
name = "Infer"
icon = "ğŸ“"
